### ISSUE TITLE
Customize with Devtools Author

### ISSUE THREAD

**Issue by huytd** [Jam3/devtool#24]
Is there any way to get this tool working with `devtool`? http://mikeking.io/devtools-author/

Actually, this is the chrome plugin, we need to make it work on Electron...

**Comment by huytd** [comment]
Hey it's possible https://github.com/atom/electron/blob/master/docs/tutorial/devtools-extension.md

**Comment by mattdesl** [comment]
Cool idea! Will explore. Probably would come through a `rc` file, see #9.

**Comment by mattdesl** [comment]
Ok, I've added RC files for themes and other features. It looks like DevTool Author does not work in Electron since it depends on `chrome.storage` and some other features. You may need to open a bug there.

However, other themes might work fine. See here:
https://github.com/Jam3/devtool/blob/master/docs/rc-config.md
