### ISSUE TITLE
[Question] How does this compare to node-inspector?

### ISSUE THREAD

**Issue by markogresak** [Jam3/devtool#5]
I have been using [node-inspector](https://github.com/node-inspector/node-inspector) for this so far, what does this project do differently?

**Comment by callmephilip** [comment]
:+1: same question here

**Comment by mik01aj** [comment]
+1, and there's also [`iron-node`](https://github.com/s-a/iron-node)...

**Comment by halhenke** [comment]
I know `node-inspector` allows you to pause execution on the first line which is really handy if you want to step through some code that you might not want to edit. `iron-node` doesn't have that yet. Would be super cool if this could pull that off :pray: 

Dont think `node-inspector` has the REPL features this does. Its a long time since i used it though because it wasnt working (for me at least) for a while there.

**Comment by mik01aj** [comment]
> I know node-inspector allows you to pause execution on the first line (...). iron-node doesn't have that yet. 

See https://github.com/s-a/iron-node/issues/35.

**Comment by halhenke** [comment]
ah - thanks. For some reason i thought i tried that and it didnt work.

**Comment by mattdesl** [comment]
I hadn't seen `iron-node` when I was developing this, and it seems to tackle the problem in a similar way.

Some features that make `devtool` a little unique:

- this is a bit more focused on command-line use and Unix-style piping/redirection (stdout/stdin)
- this embraces and promotes the Browser/Electron APIs – see the [StreetView example](https://github.com/Jam3/devtool#browser-apis) which renders a `<canvas>` to a PNG buffer, then writes the buffer to `process.stdout`
- the require hooks are modified to provide features that Electron (and `iron-node`) do not currently support, like:
  - source maps for files in the sources panel
  - more detailed syntax error messages
  - optional `"browser"` field resolution
  
`node-inspector` is built on a completely different architecture (Chrome Remote Debugging Protocol, if I understand correctly). It has its own set of pros (like native addons and a true node environment) and cons (poor GUI experience, limited set of Chrome features, can't just reload the page, etc).
  
I will do a more detailed comparison today and add it to the readme. :smile:

**Comment by markogresak** [comment]
@mattdesl Thanks for the explanation. Adding this comparison to readme would be great so visitors can find this information right away.

**Comment by mik01aj** [comment]
@mattdesl and @s-a, would you consider joining your efforts to create the ultimate debugger for Node? :D I think this could be a huge benefit for the Node community.

**Comment by halhenke** [comment]
@mattdesl :+1: great comparison

**Comment by mattdesl** [comment]
@mik01aj Once some stuff here stabilizes, I will try to split it out into separate modules so that `iron-node` (and any other potential tools) could take advantage of it.

I think it's best to keep these projects separate since they both tackle the problem in different ways, and allow for different use cases.

---

I can't actually get `node-inspector` to work right now (even just a "Hello World") so I'm having a hard time getting a feel for it. Last time I tried it, the GUI experience was clunky, things would crash often and features like profiling did not work like they do in regular Chrome. I suspect some of these things have been fixed since then, but I can't really be sure until I give it another go. :smile:

**Comment by mattdesl** [comment]
Ok, added to readme.
https://github.com/Jam3/devtool#see-also--comparisons

**Comment by halhenke** [comment]
Yeah my experiences with node-inspector have been more miss than hit - for a long time it was very much broken though i did get it to work recently.

Thats why I'm pretty excited about this project - a great debugger and a great REPL are two things that have really been missing in Node IMO.
