### ISSUE TITLE
Windows Error: Implement me. Unknown stdin file type!

### ISSUE THREAD

**Issue by jlvaquero** [Jam3/devtool#58]
This is a continuation of #42. As pushing some code to ignore process.stdin on Windows allows to open devtool window there still is a problem with stdin.

This code reproduce the error:

```
//test.js
var readline = require('readline');
var rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
  terminal: true
});

rl.on('line', function(line){
    console.log(line);
})
```

> devtool test.js < input.txt

`Error: Implement me. Unknown stdin file type!`

Windows 7 x64
S.O. Admin rights.
Node v5.10.0.
npm v3.8.3.
DevTool v1.9.1.

**Comment by mattdesl** [comment]
I have been looking into this, and unfortunately Electron dose not support `stdin` on Windows. I've fixed `devtool` so that it should not report this error anymore.

More info:
https://github.com/electron/electron/issues/4218

There may be a (much more complex) solution for Windows involving writing to a temporary file, I will file a new issue.
